[package]
name = "evaera/cmdr"
description = "A fully extensible, type-safe command framework for Roblox."
version = "1.13.0-rc.4"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://eryn.io/Cmdr/"
repository = "https://github.com/evaera/Cmdr"
realm = "shared"
exclude = ["**"]
include = [
  "assets", "assets/**",
  "Cmdr", "Cmdr/**",
  "CHANGELOG.md", "LICENSE", "README.md", "SECURITY.md",
  "wally.toml", "default.project.json"
]

[dependencies]
