[package]
name = "evaera/cmdr"
description = "A fully extensible, type-safe command framework for Roblox."
version = "1.13.0-rc.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://eryn.io/Cmdr/"
repository = "https://github.com/evaera/Cmdr"
realm = "server"
exclude = ["website", "docs", "scripts"]
include = ["CHANGELOG.md", "Cmdr", "default.project.json", "LICENSE"]

[dependencies]
